In [2]:
import numpy as np

In [4]:
arr=  np.array([1,2,3,4,5])

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr.ndim

1

In [9]:
arr.shape

(5,)

In [10]:
arr.dtype

dtype('int64')

In [3]:
b=np.array([[1,2,3],[5,6,7]])

In [16]:
b.ndim

2

In [17]:
b.shape

(2, 3)

In [4]:
b.dtype

dtype('int64')

In [5]:
b.size

6

In [20]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Matrices

In [22]:
a= np.array([1,2,3])
b=np.array([3,4,5])

In [23]:
a+b

array([4, 6, 8])

In [24]:
a-b

array([-2, -2, -2])

In [25]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])


In [27]:
dot_product = np.dot(a, b)
print(dot_product)

32


In [ ]:
import numpy as np

# Two 3D arrays
a = np.array([[[1, 2],
               [3, 4]],

              [[5, 6],
               [7, 8]]])

b = np.array([[[9, 10],
               [11, 12]],

              [[13, 14],
               [15, 16]]])

# Dot product
dot_product = np.dot(a, b)
print(dot_product)


[[[[ 31  34]
   [ 43  46]]

  [[ 71  78]
   [ 99 106]]]


 [[[111 122]
   [155 166]]

  [[151 166]
   [211 226]]]]


In [31]:
a=np.array([[1,2],[7,8]])

In [32]:
np.linalg.inv(a)

array([[-1.33333333,  0.33333333],
       [ 1.16666667, -0.16666667]])

In [33]:
np.mean(a)

np.float64(4.5)

In [34]:
np.std(a)


np.float64(3.0413812651491097)

In [35]:
np.max(a)

np.int64(8)